/* eslint-disable @next/next/no-img-element */
import type { ResumeSectionKey, ResumeTemplate } from '@/lib/types'
import { SECTION_LABELS } from '@/lib/defaults'
import { contactItems, Initials, SectionBody, type TemplateProps, visibleSections } from './template-parts'

const MAIN: ResumeSectionKey[] = ['summary', 'experience', 'projects', 'achievements']
const SIDE: ResumeSectionKey[] = ['skills', 'education', 'certifications', 'languages', 'interests']

function Photo({ url, name, className, accent }: { url?: string | null; name: string; className: string; accent: string }) {
  if (url) return <img src={url} alt="Profile" crossOrigin="anonymous" className={`${className} object-cover`} />
  return <div className={`${className} flex items-center justify-center font-bold`} style={{ backgroundColor: `${accent}12`, color: accent }}><Initials name={name}/></div>
}
function Contact({ content, light = false }: TemplateProps & { light?: boolean }) { return <div className={`flex flex-wrap gap-x-4 gap-y-1.5 text-[10.3px] ${light ? 'text-white/78' : 'text-slate-500'}`}>{contactItems(content).map((c) => <span key={c.label} className="flex items-center gap-1.5 break-all"><c.icon className="size-3 shrink-0"/>{c.label}</span>)}</div> }
function Heading({ children, accent, dark = false }: { children: React.ReactNode; accent: string; dark?: boolean }) { return <div className="mb-2.5 flex items-center gap-2"><h3 className={`shrink-0 text-[11px] font-extrabold uppercase tracking-[0.2em] ${dark ? 'text-white' : 'text-slate-900'}`} style={{ color: dark ? undefined : accent }}>{children}</h3><span className={`h-px flex-1 ${dark ? 'bg-white/18' : 'bg-slate-200'}`}/></div> }
function Shell({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`resume-document flex min-h-[1123px] w-[794px] flex-col ${className}`}>{children}</div> }

function Modern({ content, photoUrl }: TemplateProps) { const { personal, settings } = content; const accent = settings.accent || '#243B5A'; const main = visibleSections(content, MAIN); const side = visibleSections(content, SIDE); return <Shell className="bg-[#fffefd] font-sans text-[11.5px] text-slate-700"><header className="px-12 pt-10 pb-6"><div className="flex items-start justify-between gap-8"><div className="min-w-0"><p className="mb-2 text-[8.8px] font-bold uppercase tracking-[0.3em]" style={{color:accent}}>PROVIA · TAILORED RESUME</p><h1 className="text-[37px] font-black leading-[0.98] tracking-[-0.05em] text-slate-950">{personal.fullName}</h1>{personal.headline && <p className="mt-2.5 text-[14px] font-semibold text-slate-600">{personal.headline}</p>}</div>{settings.showPhoto && <Photo url={photoUrl} name={personal.fullName} accent={accent} className="size-[82px] shrink-0 rounded-xl ring-1 ring-slate-200"/>}</div><div className="mt-5 border-t border-slate-200 pt-3"><Contact content={content}/></div></header><div className="mx-12 h-[3px]" style={{backgroundColor:accent}}/><div className="grid flex-1 grid-cols-[1fr_224px] gap-9 px-12 py-7"><main>{main.map((s)=><section key={s} className="mb-6 last:mb-0"><Heading accent={accent}>{SECTION_LABELS[s]}</Heading><SectionBody content={content} section={s} accent={accent}/></section>)}</main><aside className="border-l border-slate-200 pl-6">{side.map((s)=><section key={s} className="mb-6 last:mb-0"><Heading accent={accent}>{SECTION_LABELS[s]}</Heading><SectionBody content={content} section={s} compact accent={accent} chips={s==='skills'}/></section>)}</aside></div></Shell> }

function Minimal({ content, photoUrl }: TemplateProps) { const { personal, settings } = content; const accent = settings.accent || '#39434F'; return <Shell className="bg-white px-12 py-10 font-sans text-[11.8px] text-slate-700"><header className="border-b-2 pb-5" style={{borderColor:accent}}><div className="flex items-start justify-between gap-7"><div><h1 className="text-[38px] font-black leading-none tracking-[-0.05em] text-slate-950">{personal.fullName}</h1>{personal.headline && <p className="mt-2 text-[14px] font-medium text-slate-600">{personal.headline}</p>}</div>{settings.showPhoto && <Photo url={photoUrl} name={personal.fullName} accent={accent} className="size-[68px] rounded-full"/>}</div><div className="mt-4"><Contact content={content}/></div></header><div className="mt-7 grid grid-cols-[145px_1fr] gap-x-8">{visibleSections(content).map((s)=><section key={s} className="contents"><h3 className="border-t border-slate-200 pt-4 text-[10px] font-extrabold uppercase tracking-[0.18em] first:border-0 first:pt-0" style={{color:accent}}>{SECTION_LABELS[s]}</h3><div className="border-t border-slate-200 pb-5 pt-4 first:border-0 first:pt-0"><SectionBody content={content} section={s} accent={accent}/></div></section>)}</div></Shell> }

function Executive({ content, photoUrl }: TemplateProps) { const { personal, settings } = content; const accent = settings.accent || '#7A3345'; return <Shell className="bg-[#fffdfa] px-12 py-10 font-serif text-[11.8px] text-slate-700"><header className="border-y py-6" style={{borderColor:`${accent}45`}}><div className="flex items-center justify-center gap-5 text-center"><div><p className="mb-2 font-sans text-[8.5px] font-bold uppercase tracking-[0.4em]" style={{color:accent}}>CURRICULUM VITAE</p><h1 className="text-[37px] font-semibold leading-none tracking-[0.02em] text-slate-950">{personal.fullName}</h1>{personal.headline && <p className="mt-2 text-[14px] italic text-slate-500">{personal.headline}</p>}</div>{settings.showPhoto && <Photo url={photoUrl} name={personal.fullName} accent={accent} className="size-[72px] rounded-full border"/>}</div><div className="mt-4 flex justify-center"><Contact content={content}/></div></header><div className="mt-7 grid grid-cols-[1.5fr_0.8fr] gap-9"><main>{visibleSections(content, MAIN).map((s)=><section key={s} className="mb-6"><Heading accent={accent}>{SECTION_LABELS[s]}</Heading><SectionBody content={content} section={s} accent={accent}/></section>)}</main><aside className="border-l pl-7" style={{borderColor:`${accent}30`}}>{visibleSections(content, SIDE).map((s)=><section key={s} className="mb-6"><Heading accent={accent}>{SECTION_LABELS[s]}</Heading><SectionBody content={content} section={s} compact accent={accent}/></section>)}</aside></div></Shell> }

function Professional({ content, photoUrl }: TemplateProps) { const { personal, settings } = content; const accent = settings.accent || '#39434F'; return <Shell className="bg-white font-sans text-[11.5px] text-slate-700"><header className="bg-[#18202A] px-12 py-8 text-white"><div className="flex items-center gap-5"><div className="min-w-0 flex-1"><p className="mb-1.5 text-[8.5px] font-bold uppercase tracking-[0.3em] text-white/45">PROFESSIONAL PROFILE</p><h1 className="text-[36px] font-black leading-none tracking-[-0.045em]">{personal.fullName}</h1>{personal.headline && <p className="mt-2 text-[14px] font-medium text-white/72">{personal.headline}</p>}</div>{settings.showPhoto && <Photo url={photoUrl} name={personal.fullName} accent={accent} className="size-[78px] shrink-0 rounded-lg border border-white/15"/>}</div><div className="mt-5 border-t border-white/12 pt-3"><Contact content={content} light/></div></header><div className="h-1" style={{backgroundColor:accent}}/><div className="grid flex-1 grid-cols-[1fr_226px] gap-9 px-12 py-7"><main>{visibleSections(content, MAIN).map((s)=><section key={s} className="mb-6"><Heading accent={accent}>{SECTION_LABELS[s]}</Heading><SectionBody content={content} section={s} accent={accent}/></section>)}</main><aside className="border-l border-slate-200 pl-6">{visibleSections(content, SIDE).map((s)=><section key={s} className="mb-6"><Heading accent={accent}>{SECTION_LABELS[s]}</Heading><SectionBody content={content} section={s} compact accent={accent} chips={s==='skills'}/></section>)}</aside></div></Shell> }

function Creative({ content, photoUrl }: TemplateProps) { const { personal, settings } = content; const accent = settings.accent || '#68415F'; return <Shell className="bg-[#fffdfc] font-sans text-[11.5px] text-slate-700"><header className="px-12 py-9 text-white" style={{background:`linear-gradient(120deg,#272238 0%,#3B2E4B 68%,${accent} 100%)`}}><div className="flex items-start justify-between gap-7"><div className="min-w-0"><p className="mb-2 text-[8.8px] font-bold uppercase tracking-[0.32em] text-white/50">SELECTED PROFILE</p><h1 className="text-[38px] font-black leading-[0.98] tracking-[-0.05em]">{personal.fullName}</h1>{personal.headline && <p className="mt-2.5 text-[14px] font-medium text-white/72">{personal.headline}</p>}</div>{settings.showPhoto && <Photo url={photoUrl} name={personal.fullName} accent={accent} className="size-[82px] shrink-0 rounded-[18px] border border-white/20"/>}</div><div className="mt-5"><Contact content={content} light/></div></header><div className="grid flex-1 grid-cols-[1fr_230px] gap-9 px-12 py-8"><main>{visibleSections(content, MAIN).map((s)=><section key={s} className="mb-6"><Heading accent={accent}>{SECTION_LABELS[s]}</Heading><SectionBody content={content} section={s} accent={accent}/></section>)}</main><aside className="rounded-xl border border-slate-200 bg-white px-5 py-5 shadow-[0_4px_18px_rgba(20,20,30,0.05)]">{visibleSections(content, SIDE).map((s)=><section key={s} className="mb-6 last:mb-0"><Heading accent={accent}>{SECTION_LABELS[s]}</Heading><SectionBody content={content} section={s} compact accent={accent} chips={s==='skills'}/></section>)}</aside></div></Shell> }

const TEMPLATE_COMPONENTS: Record<ResumeTemplate, (props: TemplateProps) => React.JSX.Element> = { modern: Modern, minimal: Minimal, executive: Executive, professional: Professional, creative: Creative }
export function ResumeDocument({ template, ...props }: TemplateProps & { template: ResumeTemplate }) { const Template = TEMPLATE_COMPONENTS[template] ?? Modern; return <Template {...props}/> }
